### ISSUE TITLE
你好！这个kterm是kindle那个kterm吗？

### ISSUE THREAD

**Issue by GEEKYH** [kt007007/Kterm.js#1]
![image](https://user-images.githubusercontent.com/28251455/178146936-1685e1d9-9831-4164-89a9-0574a9d9b848.png)
如果是这个的话，我最近也在找相关的程序，期待你的更新！

**Comment by kt007007** [comment]
> ![image](https://user-images.githubusercontent.com/28251455/178146936-1685e1d9-9831-4164-89a9-0574a9d9b848.png) 如果是这个的话，我最近也在找相关的程序，期待你的更新！

应该是重名了，这个是web端的仿终端插件, 不过你可以说一下你的需求我在做的时候看看能不能满足

**Comment by GEEKYH** [comment]
感谢回复 ！
受宠若惊了哈哈，不用不用，我这个需求太奇葩，因为kindle的体验版浏览器太拉跨了，连xterm都不支持，我已经快放弃了😆
